# Note: Certain tokens only work when defining a run number; they don't work anywhere else in your pipeline.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#tokens
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Service/*

pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    include:
      - Service/*

pool:
  vmImage: 'windows-2022'

variables:
  solution: 'Service/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  CI: true
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#how-can-you-reference-the-run-number-variable-within-a-script
  generatedPackageVersion: '1.0.0-CI-$(Build.BuildNumber)'
  # https://github.com/Microsoft/azure-pipelines-tasks/issues/8793#issuecomment-641196722
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]

steps:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml#allow-scripts-to-access-the-system-token
- checkout: self
  persistCredentials: true
  clean: true

# Print Version and Build Info
- script: echo '$(Build.BuildNumber)'
  displayName: Display Build Number

- script: echo '$(generatedPackageVersion)'
  displayName: Display Package Version

- script: dotnet --version
  displayName: Display dotnet version

- script: npm -v
  displayName: Display npm version
  
# Build, Test, Publish Service and Generate swagger.json
- script: dotnet build
  workingDirectory: Service
  displayName: dotnet build

- script: dotnet test
  workingDirectory: Service
  displayName: dotnet test

- script: dotnet tool restore
  workingDirectory: Service
  displayName: Install tools

- script: dotnet tool list
  workingDirectory: Service
  displayName: List tools

# TODO: Find how to get dll path from build instead of hard coding
- script: dotnet tool run swagger tofile --output ..\..\ClientGeneration\swagger.json bin\Debug\net6.0\Articles.Api.dll v1
  workingDirectory: Service\Articles.Api
  displayName: Generate swagger.json

- task: Cache@2
  displayName: Restore and Cache OpenAPI.jar downloads
  inputs:
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#key-input
    key: openapi-generator-cli
    path: ClientGeneration/downloads
    cacheHitVar: 'CACHE_HIT_OPENAPICLI'

- powershell: md downloads
  workingDirectory: ClientGeneration
  displayName: Make downloads directory
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#conditioning-on-cache-restoration
  condition: ne(variables.CACHE_HIT_OPENAPICLI, 'true')

# Download Generation Tool
- powershell: Invoke-WebRequest -OutFile openapi-generator-cli.jar https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar
  workingDirectory: ClientGeneration/downloads
  displayName: Download OpenAPI jar
  condition: ne(variables.CACHE_HIT_OPENAPICLI, 'true')

# Generate Typescript Client
- script: java -jar downloads/openapi-generator-cli.jar generate -i swagger.json -g typescript-fetch -o TypeScriptClient -c typescriptGenerationConfig.json -p=npmVersion="$(generatedPackageVersion)"
  workingDirectory: ClientGeneration
  displayName: Generate Typescript Client

- task: Cache@2
  displayName: Restore and Cache TypescriptClient/node_modules
  inputs:
    key: ClientGeneration/TypeScriptClient/package.json
    path: ClientGeneration/TypeScriptClient/node_modules
    cacheHitVar: 'CACHE_HIT_GENERATED_CLIENT_NODE_MODULES'

# Build TypescriptClient and link to client
- script: npm i
  workingDirectory: ClientGeneration/TypeScriptClient
  displayName: TypeScriptClient - npm i

- script: npm ls
  workingDirectory: ClientGeneration/TypeScriptClient
  displayName: TypeScriptClient - npm ls

- script: npm link
  workingDirectory: ClientGeneration/TypeScriptClient
  displayName: TypeScriptClient - npm link

# Install, build, and test client
- task: Cache@2
  displayName: Restore and Cache client/node_modules
  inputs:
    key: client/package-lock.json
    path: client/node_modules
    cacheHitVar: 'CACHE_HIT_CLIENT_APPLICATION_NODE_MODULES'

- task: npmAuthenticate@0
  displayName: Add auth info to client/.npmrc
  inputs:
    workingFile: 'client/.npmrc'

- script: npm i
  workingDirectory: client
  displayName: client - npm i

# Link to use generated package instead of version referenced in the package.json
- script: npm link @dotnetopenapinode/articles
  workingDirectory: client
  displayName: client - npm link @dotnetopenapinode/articles

- script: npm run build
  workingDirectory: client
  displayName: client - npm run build

- script: npm test
  workingDirectory: client
  displayName: client - npm test

- task: npmAuthenticate@0
  displayName: Add auth info to ClientGeneration/TypeScriptClient/.npmrc
  inputs:
    workingFile: 'ClientGeneration/TypeScriptClient/.npmrc'

- script: npm publish
  workingDirectory: ClientGeneration/TypeScriptClient
  displayName: TypeScriptClient - npm publish

# Install published package into client
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax
- powershell: |
    $packagename = npm ls | select-object -first 1 | select-string -Pattern '.[^@]+@[^\s]+' | foreach {$_.Matches.Value}
    Write-Host "##vso[task.setvariable variable=PackageName;]$packagename"
  workingDirectory: ClientGeneration/TypeScriptClient
  displayName: Get @dotnetopenapinode/articles package version

- script: npm add $(PackageName) --save-exact
  workingDirectory: client
  displayName: Install @dotnetopenapinode/articles into client

- script: npm ls
  workingDirectory: client
  displayName: Verify install into client

# Commit updated package change back to branch
# https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml#how-do-i-avoid-triggering-a-ci-build-when-the-script-pushes
- script: |
    git config --global user.email "noreply@fastmail.com"
    git config --global user.name "Build Pipeline"
    git add client/package.json
    git add client/package-lock.json
    git commit -m "chore(build): update @dotnetopenapinode/articles package [skip ci]"
    git checkout -b temp-branch
    git checkout $(branchName)
    git merge temp-branch
    git push
  displayName: Create commit of package changes and push commit to branch
  condition: and(succeeded(), eq(variables.isMain, 'true'))